# Generated by Django 3.2 on 2021-11-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('patientId', models.IntegerField(primary_key=True, serialize=False)),
                ('deviceId', models.IntegerField(unique=True)),
                ('hour', models.DateTimeField()),
                ('type', models.IntegerField()),
            ],
        ),
    ]
