# Generated by Django 3.2 on 2021-11-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='glucoseValue',
            field=models.IntegerField(default=54),
            preserve_default=False,
        ),
    ]
